### ISSUE TITLE
Select not working

### ISSUE THREAD

**Issue by Morlack** [coniel/meteor-react-form-handler-material-ui#2]
Hey coniel,

first off, thanks a lot for making this package. I'm coming from blaze to react and this form lib is really useful! I have one problem however, which is that the select box is not working. 

Consider the following component: 

```
NewProjectForm = React.createClass({

    render() {
        return (
            <Form schema={this.getSchema()} id="registration-form" onSubmit={this._onSubmit}>
                <TextInput name="projectName" layoutStyle="first-half"/>
                <Select name="databaseType" options={[{label: 'None', value: 'none'}, {label: 'Oracle', value: 'oracle'}]} />
                <SubmitButton label="Create Project" />
            </Form>
        )
    },

    getSchema() {
        return new SimpleSchema({
            projectName: {
                type: String,
                max: 60,
                placeholder: "My testable project"
            },
            databaseType: {
                type: String,
                allowedValues: [],
                placeholder: 'My database type'
            }
        });
    },
    _onSubmit() {

    }
});
```

It renders the field, dropdown button and label correctly. However, no items seem to get rendered. I have attached a screenshot of the result. 
![ndgaq4h](https://cloud.githubusercontent.com/assets/3278878/12507617/2556ea4a-c0f7-11e5-80c2-f41e10237881.png)

**Comment by Morlack** [comment]
Hey there again, 

I got it fixed. It would be nice to include in the README.md that you need add your coniel:react-tap-event-plugin@0.0.3 to execute this code when you bootstrap your meteor application:

```
injectTapEventPlugin();
```

Without this, it does NOT work out of the box.

**Comment by coniel** [comment]
Hey, thanks for opening an issue, glad you like the package! I also struggled with the exact same issue you had for a while, I had planned to add that to the readme, but totally forgot. I'll add it now, thanks for the reminder!
